### PR TITLE
Documentation rewrite and site redesign

### PR DESCRIPTION
**Pull request by mylesagray**
Hi all,

As discussed on SIG-VMware meeting, I have rewritten the doc site in almost its entirety, including styles and layouts.

A staging site can be found here: http://mylesagray.github.io/vsphere-storage-for-kubernetes/documentation/index.html

## Included changes in this PR:

* Removal of all extraneous information relating to pre 1.9.x
* Refactored all docs to include more thought out flow for each section
* Reformatted all docs to conform with [Markdownlint](https://github.com/DavidAnson/markdownlint) as far as possible.
* Added tables of contents to all documents
* Deduplicated content and ratified all dispersed info into a single source of truth
* Added links to sections that follow on from each other to allow for better flow
* Rewrote large portions of the docs for better grammar, spelling and made more succinct
* Covered areas that I had problems with as a new adopter and clarified, expanded upon those
* Made dynamic provisioning the preferred method for storage consumption and downplayed (but still included static provisioning) as static was very predominant in master.
* Removed references and instructions relating to K8s `Volumes` - different to `PersistentVolumes` as I found these confusing as a new user and are very rarely every used.

## Things I could not update needing attention:

* Version list with features included, up to 1.14
* Known issues list
* Should we explore importing the YAML files held for the examples [in `vmware/k`](https://github.com/vmware/kubernetes/tree/kube-examples/kube-examples/) into this repo as some links have gone dead on `k/k` [e.g.](https://github.com/Kubernetes/Kubernetes/tree/master/examples/volumes/vsphere)?

## Pages for redirection/removal

At this stage I have not deleted any orphaned pages - I would rather 301 these to the homepage, but the sections that are in scope for this are:

* `bestpractises.md`
* `kubernetes-volumes.md`
* `statefulsets.md`
* `storageclass.md`

## Areas that still need work:

* `high-availability.md`
* `known-issues.md` (Perhaps just link to `sig/vmware` tag on `k/k`?)
* `kubernetes-update.md`
* `maximum-scale-limit.md`
* `saml-token-authentication.md`
* `troubleshooting.md`
* `vcp-roles.md` (should we have a one liner install script that does this for users?)
* Generic install section including `kubeadm` instructions from [my blogs](http://blah.cloud/course/k8s-on-vmw/)
* Generic upgrade section for `kubeadm` upgrades
* Upgrade section for non-`kubeadm` installs

Myles

### CODE REVIEW

**Comment by rhockenbury** [comment]
Might be a good idea to mention the state of VCP on windows, since it's GA now.  As far as I know, zones (labeling) are supported, but attaching storage to a windows pod is not.

**Comment by mylesagray** [comment]
@rhockenbury - I have no experience with running K8S or the VCP on Windows, if you have any information it would be greatly appreciated.

**Comment by rhockenbury** [comment]
@SandeepPissay @benmoss @astrieanna Would any of you be able to assist in understanding and/or documenting the current state of VCP with windows nodes?

**Comment by SandeepPissay** [comment]
@rhockenbury I have not deployed VCP/K8s on windows. I wont be able to help here.

**Comment by benmoss** [comment]
I'll take a look and see what I can add

**Comment by divyenpatel** [comment]
@mylesagray Can you clean up known issues page as part of this effort - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/known-issues.html

Issues mentioned here are no longer relevant, as those releases are deprecated and not supported.
We should document about known issues from newer releases (v1.14, v1.13, v1.12 and v.11).

**Comment by divyenpatel** [comment]
@mylesagray Please correct contact us page as well - https://mylesagray.github.io/vsphere-storage-for-kubernetes/documentation/contactus.html

Issues link is pointing to archived repository - https://github.com/vmware/kubernetes
Email alias `hatchway@vmware.com` seems no longer valid.

**Comment by divyenpatel** [comment]
@mylesagray 
One more thing. Can you direct user to visit https://github.com/kubernetes/cloud-provider-vsphere for CSI Driver.

Steps for deploying CSI driver is already documented - https://github.com/kubernetes/cloud-provider-vsphere/tree/master/docs, which can be moved here.

**Comment by benmoss** [comment]
I unfortunately don't have anything to contribute. I tried to create a pod with a persistent volume claim attached but it appears not to work on Windows. I don't know enough about how it should work to find out where it's going wrong, but it looks like it's just not being attached to the node. 

From the kubelet logs the most helpful I see is: `Error: "Volume has not been added to the list of VolumesInUse in the node's volume status`

**Comment by mylesagray** [comment]
@divyenpatel I have integrated some changes you requested and resolved merge conflicts - I have not directed CSI content to here as we have a different content plan for this, currently in place here: https://github.com/kubernetes/cloud-provider-vsphere/pull/181

Those efforts may be redirected here, but we have yet to figure that out.

I have also updated the instructions on the existing clusters page as I found some holes in it.

The plan currently is to write documentation there for CCM and CSI and then upstream to SIG-Docs into the docs.k8s.io platform. That should be the centralised source for K8s docs, not individual repos or micro-sites.

As for the known issues in 1.11, 1.12, 1.13 and 1.14 - I have no info on these, perhaps this is something we can work on together after merge?

Myles

**Comment by divyenpatel** [comment]
LGTM

**Pull request merged**
