### PR TITLE
Minor grammar improvements to documentation

### PR DESCRIPTION
**Pull request by ellieayla**
Minor grammar improvements to documentation

### CODE REVIEW

**Comment by ellieayla** [comment]
One of these changes might be irrelevant given pull request #1

**Comment by divyenpatel** [comment]
lgtm

**Comment by divyenpatel** [comment]
thanks @alanjcastonguay for making the change.

@tusharnt Can we merge this PR?

**Comment by divyenpatel** [comment]
Updated site with the changes made in this PR - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/index.html

**Pull request merged**
